### ISSUE TITLE
Wire UI and Service together

### ISSUE THREAD

**Issue by wiseodd** [pumpkinz/pumpkin-reader#20]
@timotiusnc feel free to add

What UI needs from Service -> methods to:
1. Get N first news, with pagination support, by news type (Top, New, AskHN, ShowHN, and Job)
2. Get all comments given a news item, with their children recursively

**Comment by timotiusnc** [comment]
Sample scenario for first time usage:
1. User opens app.
2. App requests `/topnews.json` and store its 500 return values into `SharedPreferences`.
3. App requests topnews 1 to N (without comment), store it into SQLite, then display it.
4. `-----------------------------------`
4. User scrolls down, triggering next page action.
5. App requests topnews N+1 to 2N (still without comment), store it into SQLite, then append it to previous topnews.
6. `-----------------------------------`
6. User taps on a news, triggering NewsDetailActivity.
7. App requests **all** comments (recursively) on that corresponding topnews, store it into SQLite, then display it.
8. `-----------------------------------`
8. User closes the app, then re-opens it.
9. App checks `SharedPreferences`, it already contains values from `/topnews.json`, App retrieves it.
10. Knowing the `SharedPreferences` already contains values from `/topnews.json`, App get topnews 1 to N from SQLite.
11. `-----------------------------------`
11. User refreshes the app (pull-down-to-refresh?).
12. App requests `/topnews.json` again and replace the 500 values in `SharedPreferences` with these new values.
13. App requests topnews 1 to N, for each topnews, App queries the SQLite (`SELECT * FROM topnews WHERE _ID IN (95843, 23934, 987413, ... )`) [If some topnews do not exist in SQLite, App will requests those topnews, write it to SQLite, and append it to the return values].
14. The same thing happens for comments everytime user refreshes the NewsDetailActivity (the difference for comment is App will update the comments in SQLite rather than SharedPreferences [because topnews are stored in SQLite]).

What do you think @wiseodd?

## 

Reminder for me to think about this later:
1. As time goes on, the topnews in SQLite will get bigger and bigger -> Decice a life span of a topnews in SQLite OR a duration to purge the entire SQLite and SharedPreferences periodically.
2. For better user experience, App might need to refresh the topnews automatically -> Think how often App shall do this and how.

**Comment by wiseodd** [comment]
Please study this app:
https://play.google.com/store/apps/details?id=free.reddit.news&hl=en

Generally, it's just like what you've said, with some differences:
1. No need for SharedPreferences to store topnews ids. Just rerequest it.
2. No need to refresh the news automatically. Let the user in full control, as a user I wouldn't want the news list refreshs itself while I'm still reading.

Anyway, please prioritize on two methods I've stated at the first post.
Let's finisih them first, without caching, etc.

After we've done that, we can start thinking about optimization.

**Comment by timotiusnc** [comment]
Right, it's funny how I could forget that Knuth's wisdom, even after all this time.

Dumbledore: "After all this time?"
Snape: "Always"
